[package]
name = "alns"
version = "0.1.0"
authors = ["Pocket7878 <poketo7878@gmail.com>"]
edition = "2018"

[lib]
name = "alns_rs"
path = "src/lib.rs"

[[bin]]
name = "alns"
path = "src/main.rs"

[dependencies]
rand = "0.8.0"
tspf = "0.3.0"